# This file provides instructions for packaging.

`Trait-Attribute-Derived`
	perl_version_from m`Trait::Attribute::Derived`;
	version_from      m`Trait::Attribute::Derived`;
	readme_from       m`Trait::Attribute::Derived`;
	test_requires     p`Test::More 0.61` ;
	.

