# This file provides instructions for packaging.

`Trait-Attribute-Derived`
	perl_version_from m`Trait::Attribute::Derived`;
	version_from      m`Trait::Attribute::Derived`;
	readme_from       m`Trait::Attribute::Derived`;
	requires          p`MooseX::Role::Parameterized 0`;
	requires          p`Sub::Install 0`;
	requires          p`Sub::NonRole 0.002`;
	requires          p`namespace::autoclean 0`;
	requires          p`Moose 2.00`;
	.

